#!/usr/bin/env python3
"""
Printer CFG Generator — YUMI C-Series
Generates a complete printer.cfg from YUMI-LAB_product-catalog.json.

Usage:
    python3 generator.py C235_DD_LW_04
    python3 generator.py C235_CX12_HF_04_7YMS -o /tmp/printer.cfg
    python3 generator.py --list
"""
import json
import copy
import sys
import argparse
from pathlib import Path

BASE_DIR = Path(__file__).parent
CATALOG_FILE = BASE_DIR / "YUMI-LAB_product-catalog.json"


# ─── Catalog loader ─────────────────────────────────────────────────

def load_catalog():
    with open(CATALOG_FILE) as f:
        return json.load(f)


def deep_merge(base, override):
    result = copy.deepcopy(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = deep_merge(result[key], val)
        else:
            result[key] = copy.deepcopy(val)
    return result


def resolve_product(product_id):
    catalog = load_catalog()
    products = catalog.get("products", {})
    components = catalog.get("components", {})

    if product_id not in products:
        print(f"ERROR: Product '{product_id}' not found.")
        print(f"Available: {', '.join(k for k, v in products.items() if isinstance(v, dict) and 'chain' in v)}")
        sys.exit(1)

    product_def = products[product_id]
    chain = product_def["chain"]

    for comp_id in chain:
        if comp_id not in components:
            print(f"ERROR: Component '{comp_id}' not found.")
            sys.exit(1)

    # Check incompatibilities
    chain_set = set(chain)
    for comp_id in chain:
        comp = components[comp_id]
        for forbidden in comp.get("incompatible_with", []):
            if forbidden in chain_set:
                print(f"ERROR: '{comp_id}' is incompatible with '{forbidden}'.")
                sys.exit(1)

    # Deep merge all components
    skip_keys = {"layer", "children", "terminates", "incompatible_with", "parent",
                 "requires", "requires_any", "terminates_if", "yms_constraints",
                 "max_instances", "_TODO"}
    merged = {}
    for comp_id in chain:
        comp = components[comp_id]
        data = {k: v for k, v in comp.items() if k not in skip_keys}
        if "config" in data:
            cfg = data.pop("config")
            data.update(cfg)
        merged = deep_merge(merged, data)

    merged["name"] = product_def["name"]
    merged["_chain"] = chain
    return merged


# ─── Condition evaluator ────────────────────────────────────────────

def check_condition(condition, product):
    if condition == "always":
        return True
    if condition.startswith("feature:"):
        feat = condition.split(":", 1)[1]
        return product.get("features", {}).get(feat, False)
    if condition == "yms_count > 0":
        return product.get("yms_count", 0) > 0
    if condition == "has_dryer":
        return product.get("has_dryer", False)
    if condition == "has_smartbox":
        return product.get("has_smartbox", False)
    return True


# ─── Hardware section renderers (from data, not hardcoded gcode) ────

def render_header(p):
    yms = p.get('yms_count', 0)
    bed = p.get('bed_size', 0)
    return f"""########################################################################
# {p['name']}
# Bed: {bed}x{bed}mm — Z: {p.get('z_height', 0)}mm — {p.get('kinematics', 'cartesian')}
# YMS: {yms}
# Generated by Printer CFG Generator
########################################################################"""


def render_includes(p):
    lines = []
    feat = p.get('features', {})
    if feat.get('plr'):
        lines.append("[include plr.cfg]")
    if feat.get('timelapse'):
        lines.append("[include timelapse.cfg]")
    if feat.get('obico'):
        lines.append("[include moonraker_obico_macros.cfg]")
    return "\n".join(lines)


def render_probe_pressure(p):
    if not p.get('features', {}).get('probe_pressure'):
        return ""
    pp = p.get('probe_pressure', {})
    return f"""[probe_pressure]
pin: {pp.get('pin', '!PB7')}
speed: {pp.get('speed', 6.0)}
lift_speed: {pp.get('lift_speed', 6)}

[yumi_z_tap]
pressure_switch_x: {pp.get('z_calc_switch_x', 49.5)}
pressure_switch_y: {pp.get('z_calc_switch_y', 175.5)}
compression_offset: {pp.get('compression_offset', 0.3)}
max_probe_times: {pp.get('max_probe_times', 50)}
probe_delay: {pp.get('probe_delay', 2)}
z_hop: {pp.get('z_hop', 3)}
samples: {pp.get('samples', 5)}
samples_tolerance: {pp.get('samples_tolerance', 0.01)}"""


def render_motor_constants(p):
    lines = []
    for name, mc in p.get('motor_constants', {}).items():
        lines.append(f"[motor_constants {name}]")
        for k, v in mc.items():
            lines.append(f"{k}: {v}")
        lines.append("")
    return "\n".join(lines).rstrip()


def render_tmc_autotune(p):
    if not p.get('features', {}).get('tmc_autotune'):
        return ""
    at = p.get('tmc_autotune', {})
    ep = at.get('extruder', {})
    lines = []

    for axis in ['x', 'y', 'z']:
        sa = p.get(f'stepper_{axis}', {})
        motor = sa.get('motor', '')
        if not motor:
            continue
        # Per-axis params with fallback to shared 'stepper' key
        sp = at.get(f'stepper_{axis}', at.get('stepper', {}))
        lines.append(f"[autotune_tmc stepper_{axis}]")
        lines.append(f"motor: {motor}")
        lines.append("tuning_goal: auto")
        for k, v in sp.items():
            lines.append(f"{k}: {v}")
        lines.append("")

    yms = p.get('yms_count', 0)
    ext = p.get('extruder', {})
    motor = ext.get('motor', '')
    if motor:
        if yms == 0:
            lines.append("[autotune_tmc extruder]")
        else:
            for i in range(yms):
                if i > 0:
                    lines.append("")
                lines.append(f"[autotune_tmc extruder_stepper extruder{i}]")
        lines.append(f"motor: {motor}")
        lines.append("tuning_goal: auto")
        for k, v in ep.items():
            lines.append(f"{k}: {v}")
        lines.append("")

    return "\n".join(lines).rstrip()


def render_mcu(p):
    mcu = p.get('mcu', {})
    return f"""[mcu]
serial: {mcu.get('serial', '/dev/ttyS1')}
restart_method: {mcu.get('restart_method', 'command')}"""


def render_smartbox_mcu(p):
    if not p.get('has_smartbox', False):
        return ""
    sb = p.get('smartbox', {})
    name = sb.get('mcu_name', 'smartbox')
    return f"""[mcu {name}]
serial: {sb.get('serial', '/dev/ttyS2')}
restart_method: {sb.get('restart_method', 'command')}"""


def render_printer(p):
    return f"""[printer]
kinematics: {p.get('kinematics', 'cartesian')}
max_velocity: {p.get('max_velocity', 700)}
max_accel: {p.get('max_accel', 20000)}
max_z_velocity: {p.get('max_z_velocity', 25)}
max_z_accel: {p.get('max_z_accel', 1000)}"""


def render_adxl(p):
    if not p.get('features', {}).get('adxl'):
        return ""
    bed = p.get('bed_size', 235)
    return f"""[mcu rpi]
serial: /tmp/klipper_host_mcu

[adxl345]
cs_pin: rpi:gpio13
spi_bus: spidev1.0

[resonance_tester]
accel_chip: adxl345
probe_points:
    {bed / 2}, {bed / 2}, 20

[input_shaper]"""


def render_steppers(p):
    lines = []
    for axis in ['x', 'y']:
        s = p.get(f'stepper_{axis}', {})
        lines.append(f"[stepper_{axis}]")
        for pin in ['step_pin', 'dir_pin', 'enable_pin']:
            if pin in s:
                lines.append(f"{pin}: {s[pin]}")
        lines.append("microsteps: 16")
        lines.append("rotation_distance: 40")
        lines.append(f"endstop_pin: tmc2209_stepper_{axis}: virtual_endstop")
        for k in ['position_endstop', 'position_min', 'position_max', 'homing_speed']:
            if k in s:
                lines.append(f"{k}: {s[k]}")
        lines.append("homing_retract_dist: 0")
        lines.append("")
        lines.append(f"[tmc2209 stepper_{axis}]")
        if 'uart_pin' in s:
            lines.append(f"uart_pin: {s['uart_pin']}")
        for k in ['run_current', 'hold_current']:
            if k in s:
                lines.append(f"{k}: {s[k]}")
        lines.append("stealthchop_threshold: 0")
        if 'driver_sgthrs' in s:
            lines.append(f"driver_sgthrs: {s['driver_sgthrs']}")
        if 'diag_pin' in s:
            lines.append(f"diag_pin: {s['diag_pin']}")
        lines.append("")

    # Z
    sz = p.get('stepper_z', {})
    lines.append("[stepper_z]")
    for pin in ['step_pin', 'dir_pin', 'enable_pin']:
        if pin in sz:
            lines.append(f"{pin}: {sz[pin]}")
    lines.append("microsteps: 16")
    lines.append("rotation_distance: 8")
    lines.append("endstop_pin: probe:z_virtual_endstop")
    for k in ['position_max', 'position_min', 'homing_speed', 'second_homing_speed']:
        if k in sz:
            lines.append(f"{k}: {sz[k]}")
    lines.append("homing_retract_dist: 5")
    lines.append("")
    lines.append("[tmc2209 stepper_z]")
    if 'uart_pin' in sz:
        lines.append(f"uart_pin: {sz['uart_pin']}")
    for k in ['run_current', 'hold_current']:
        if k in sz:
            lines.append(f"{k}: {sz[k]}")
    lines.append("stealthchop_threshold: 0")

    return "\n".join(lines)


def render_thermistor(p):
    t = p.get('thermistor', {})
    return f"""[thermistor {t.get('name', '100K4190YUMI')}]
temperature1: {t.get('temperature1', 25)}
resistance1: {t.get('resistance1', 100000)}
beta: {t.get('beta', 4300)}"""


def render_extruder(p):
    e = p.get('extruder', {})
    lines = []
    lines.append("[extruder]")
    lines.append("max_extrude_only_velocity: 500")
    for pin in ['step_pin', 'dir_pin', 'enable_pin']:
        if pin in e:
            lines.append(f"{pin}: {e[pin]}")
    for k in ['rotation_distance', 'gear_ratio']:
        if k in e:
            lines.append(f"{k}: {e[k]}")
    lines.append("microsteps: 16")
    lines.append("full_steps_per_rotation: 200")
    nd = e.get('nozzle_diameter', p.get('nozzle_diameter', 0.4))
    lines.append(f"nozzle_diameter: {nd}")
    lines.append("filament_diameter: 1.750")
    for pin in ['heater_pin', 'sensor_pin']:
        if pin in e:
            lines.append(f"{pin.replace('_pin', '_pin' if pin.endswith('_pin') else '')}: {e[pin]}")
    if 'sensor_type' in e:
        lines.append(f"sensor_type: {e['sensor_type']}")
    if 'heater_pin' in e:
        lines.append(f"heater_pin: {e['heater_pin']}")
    if 'sensor_pin' in e:
        lines.append(f"sensor_pin: {e['sensor_pin']}")
    lines.append(f"min_temp: -200")
    lines.append(f"max_temp: {e.get('max_temp', 300)}")
    lines.append("max_extrude_only_distance: 8000.0")
    lines.append("max_extrude_cross_section: 40")
    lines.append(f"min_extrude_temp: {e.get('min_extrude_temp', 0)}")
    lines.append("pressure_advance: 0")
    lines.append("control: pid")
    lines.append(f"pid_Kp: {e.get('pid_Kp', p.get('pid_Kp', 26.213))}")
    lines.append(f"pid_Ki: {e.get('pid_Ki', p.get('pid_Ki', 1.304))}")
    lines.append(f"pid_Kd: {e.get('pid_Kd', p.get('pid_Kd', 131.721))}")

    # TMC for single extruder
    if p.get('yms_count', 0) == 0:
        lines.append("")
        lines.append("[tmc2209 extruder]")
        if 'uart_pin' in e:
            lines.append(f"uart_pin: {e['uart_pin']}")
        lines.append(f"run_current: {e.get('run_current', 1.2)}")
        lines.append(f"hold_current: {e.get('hold_current', 0.3)}")
        lines.append("stealthchop_threshold: 0")

    return "\n".join(lines)


def render_filament_sensor_single(p):
    if p.get('yms_count', 0) > 0:
        return ""
    slots = p.get('extruder_slots', [])
    pin = slots[0]['filament_sensor_pin'] if slots else "!PC14"
    return f"""[filament_motion_sensor filament_sensor]
switch_pin: {pin}
detection_length: 50
extruder: extruder
pause_on_runout: True
event_delay: 0.0001
runout_gcode:
    {{% set print_state = printer.print_stats.state %}}
    {{% if print_state in ['printing', 'paused'] %}}
        PAUSE
        RESPOND TYPE=error MSG="Filament runout detected!"
        M117 Filament runout detected!
    {{% else %}}
        RESPOND TYPE=error MSG="Filament removed (not printing)"
        M117 Filament removed
    {{% endif %}}
insert_gcode:
    RESPOND MSG="Filament inserted\""""


def render_yms_extruders(p):
    if p.get('yms_count', 0) == 0:
        return ""
    yms_count = p['yms_count']
    e = p.get('extruder', {})
    lines = []

    all_slots = list(p.get('extruder_slots', []))
    if p.get('has_smartbox'):
        sb = p.get('smartbox', {})
        for slot in sb.get('extruder_slots', []):
            s = dict(slot)
            s['mcu'] = sb.get('mcu_name', 'smartbox')
            all_slots.append(s)

    for i in range(min(yms_count, len(all_slots))):
        slot = all_slots[i]
        mcu = f"{slot['mcu']}:" if slot.get('mcu') and slot['mcu'] != 'main' else ""
        rot_dist = 22.6789511 if i != 1 else e.get('rotation_distance', 25)

        lines.append(f"[extruder_stepper extruder{i}]")
        lines.append("extruder:")
        lines.append(f"step_pin: {mcu}{slot['step_pin']}")
        lines.append(f"dir_pin: {mcu}{slot['dir_pin']}")
        lines.append(f"enable_pin: {mcu}{slot['enable_pin']}")
        lines.append("microsteps: 16")
        lines.append(f"rotation_distance: {rot_dist}")
        lines.append(f"gear_ratio: {e.get('gear_ratio', '50:17')}")
        lines.append("full_steps_per_rotation: 200")
        lines.append("pressure_advance: 0.0")
        lines.append("")
        lines.append(f"[tmc2209 extruder_stepper extruder{i}]")
        lines.append(f"uart_pin: {mcu}{slot['uart_pin']}")
        lines.append(f"run_current: {e.get('run_current', 1.2)}")
        lines.append(f"hold_current: {e.get('hold_current', 0.3)}")
        lines.append("stealthchop_threshold: 0")
        lines.append("")

        # Filament sensor
        yms_num = i + 1
        sensor_type = "filament_yumi_smart_motion_sensor" if i == 1 else "filament_motion_sensor"
        sensor_pin = slot.get('filament_sensor_pin', '')
        lines.append(f"[{sensor_type} YMS-{yms_num}]")
        lines.append(f"switch_pin: {mcu}{sensor_pin}")
        lines.append("detection_length: 50")
        lines.append("pause_on_runout: False")
        lines.append("extruder: extruder")
        if i == 0:
            lines.append("event_delay: 0.0001")
        if i == 1:
            lines.append("blockage_detection: True")
            lines.append("min_pitch: 0.7")
            lines.append("max_pitch: 2.6")
            lines.append("blockage_threshold: 2")
            lines.append("reset_motion_sensor_threshold: 16")
            lines.append("pitch_view: True")
            lines.append("low_pitch_filter: 0.015")
        lines.append("runout_gcode:")
        lines.append(f"  SAVE_VARIABLE VARIABLE=yms{yms_num}_sensor VALUE=False")
        lines.append("   {% set print_state = printer.print_stats.state %}")
        lines.append("    {% if print_state in ['printing', 'paused'] %}")
        lines.append("        PAUSE")
        lines.append(f"        RESPOND TYPE=error MSG=\"YMS-{yms_num} filament encoder runout\"")
        lines.append("    {% else %}")
        lines.append(f"        RESPOND TYPE=error MSG=\"YMS-{yms_num} No printing running!\"")
        lines.append("    {% endif %}")
        lines.append("insert_gcode:")
        lines.append(f"  SAVE_VARIABLE VARIABLE=yms{yms_num}_sensor VALUE=True")
        lines.append("  {% if printer.save_variables.variables.printing_start %}")
        lines.append(f"        T{i}")
        lines.append("  {% else %}")
        lines.append(f"        T{i+1}")
        lines.append("  {% endif %}")
        lines.append(f"  M117 YMS-{yms_num} Loading")
        lines.append("  LOAD_YMS")
        lines.append("")

        # Dryer after YMS-3
        if i == 2 and p.get('has_dryer') and p.get('has_smartbox'):
            sb = p.get('smartbox', {})
            d = sb.get('dryer', {})
            mcu_name = sb.get('mcu_name', 'smartbox')
            lines.append(f"""[heater_generic YMS-3-PRO]
heater_pin: {mcu_name}:{d.get('heater_pin', 'PC8')}
sensor_type: 100K4190YUMI
sensor_pin: {mcu_name}:{d.get('sensor_pin', 'PC1')}
max_power: 1
control: pid
pid_Kp: 50
pid_Ki: 50
pid_Kd: 50
min_temp: -50
max_temp: 110

[heater_fan dryer_fan]
pin: {mcu_name}:{d.get('fan_pin', 'PC6')}
max_power: 1
off_below: 0.31
heater: YMS-3-PRO
heater_temp: 25
shutdown_speed: 0

[verify_heater YMS-3-PRO]
max_error: 180000
check_gain_time: 3000
hysteresis: 10
heating_gain: 2
""")

    return "\n".join(lines).rstrip()


def render_heater_bed(p):
    hb = p.get('heater_bed', {})
    return f"""[heater_bed]
heater_pin: {hb.get('heater_pin', 'PC9')}
sensor_type: {hb.get('sensor_type', 'EPCOS 100K B57560G104F')}
sensor_pin: {hb.get('sensor_pin', 'PC0')}
control: pid
pid_Kp: {hb.get('pid_Kp', 27.486)}
pid_Ki: {hb.get('pid_Ki', 0.306)}
pid_Kd: {hb.get('pid_Kd', 617.406)}
min_temp: 0
max_temp: {hb.get('max_temp', 130)}"""


def render_verify_heaters():
    return """[verify_heater extruder]
max_error: 500
check_gain_time: 20
hysteresis: 20
heating_gain: 2

[verify_heater heater_bed]
max_error: 500
hysteresis: 10"""


def render_fans(p):
    f = p.get('fans', {})
    lines = []
    lines.append(f"[fan]\npin: {f.get('part_cooling', 'PC7')}")
    lines.append(f"""
[heater_fan hotend_fan]
pin: {f.get('hotend', 'PC6')}
max_power: 1
kick_start_time: 0.5
heater: extruder
heater_temp: 50.0
fan_speed: 1
shutdown_speed: 1.0""")
    lines.append(f"""
[controller_fan Motherboard_Fan]
pin: {f.get('motherboard', 'PB8')}
fan_speed: {f.get('motherboard_speed', 0.7)}
idle_timeout: {f.get('motherboard_idle_timeout', 10)}
idle_speed: 0
kick_start_time: 0.01
off_below: 0.1""")

    if p.get('has_smartbox'):
        sb = p.get('smartbox', {})
        sb_fan = sb.get('fans', {}).get('box_fan', 'PB8')
        mcu = sb.get('mcu_name', 'smartbox')
        lines.append(f"""
[controller_fan smartbox_Fan]
pin: {mcu}:{sb_fan}
fan_speed: 1
idle_timeout: 10
idle_speed: 0
kick_start_time: 0.01
off_below: 0.1""")

    lines.append(f"\n[fan_generic Aux_Fan]\npin: {f.get('aux', 'PA2')}")
    return "\n".join(lines)


def render_temp_sensors():
    return """[temperature_sensor NanoPi]
sensor_type: temperature_host
min_temp: 0
max_temp: 100"""


def render_probe(p):
    pr = p.get('probe', {})
    return f"""[probe]
pin: {pr.get('pin', 'PA14')}
x_offset: {pr.get('x_offset', -17)}
y_offset: {pr.get('y_offset', 30)}
z_offset: 0
speed: 5
samples: {pr.get('samples', 6)}
samples_result: {pr.get('samples_result', 'average')}
sample_retract_dist: 2
samples_tolerance: {pr.get('samples_tolerance', 0.08)}
samples_tolerance_retries: {pr.get('samples_tolerance_retries', 10)}"""


def render_bed_mesh(p):
    bm = p.get('bed_mesh', {})
    return f"""[bed_mesh]
speed: {bm.get('speed', 120)}
horizontal_move_z: {bm.get('horizontal_move_z', 10)}
mesh_min: {bm.get('mesh_min', '10, 10')}
mesh_max: {bm.get('mesh_max', '223, 225')}
probe_count: {bm.get('probe_count', '10, 10')}
algorithm: bicubic
zero_reference_position: {bm.get('zero_reference_position', '100.5, 147.5')}
adaptive_margin: {bm.get('adaptive_margin', 5)}"""


def render_screws_tilt(p):
    st = p.get('screws_tilt', {})
    return f"""[screws_tilt_adjust]
screw1: {st.get('screw1', '49.5, 175.5')}
screw1_name: {st.get('screw1_name', 'front left screw')}
screw2: {st.get('screw2', '224, 175.5')}
screw2_name: {st.get('screw2_name', 'front right screw')}
screw3: {st.get('screw3', '224, 2')}
screw3_name: {st.get('screw3_name', 'rear right screw')}
screw4: {st.get('screw4', '49.5, 2')}
screw4_name: {st.get('screw4_name', 'rear left screw')}
horizontal_move_z: {st.get('horizontal_move_z', 10)}
speed: {st.get('speed', 200)}
screw_thread: {st.get('screw_thread', 'CCW-M3')}"""


def render_yms_tool_macros(p):
    """Generate T0-TN, TOFF, CURRENT_UNLOAD, SET_PRESSURE_ADVANCE for YMS."""
    yms_count = p.get('yms_count', 0)
    if yms_count == 0:
        return ""

    lines = []
    all_ext = [f"extruder{i}" for i in range(yms_count)]

    # TOFF
    lines.append("[gcode_macro TOFF]")
    lines.append("description: Disable all extruders")
    lines.append("gcode:")
    for i in range(yms_count):
        lines.append(f"    SET_FILAMENT_SENSOR SENSOR=YMS-{i+1} ENABLE=0")
    lines.append("    SYNC_EXTRUDER_MOTION EXTRUDER=extruder MOTION_QUEUE=extruder")
    for name in all_ext:
        lines.append(f"    SYNC_EXTRUDER_MOTION EXTRUDER={name} MOTION_QUEUE=\"\"")
    lines.append("    RESPOND MSG=\"DISABLE ALL YMS\"")
    lines.append("")

    # T0 (special — init mode)
    lines.append("[gcode_macro T0]")
    lines.append("description: ACTIVATE YMS-1 OR INSERT_DETECTION")
    lines.append("gcode:")
    lines.append("  {% set svv = printer.save_variables.variables %}")
    lines.append("  {% if printer.save_variables.variables.printing_start %}")
    for i in range(yms_count):
        lines.append(f"    SET_FILAMENT_SENSOR SENSOR=YMS-{i+1} ENABLE={'1' if i == 0 else '0'}")
    lines.append("    SYNC_EXTRUDER_MOTION EXTRUDER=extruder MOTION_QUEUE=extruder")
    lines.append("    SYNC_EXTRUDER_MOTION EXTRUDER=extruder0 MOTION_QUEUE=extruder")
    for name in all_ext[1:]:
        lines.append(f"    SYNC_EXTRUDER_MOTION EXTRUDER={name} MOTION_QUEUE=\"\"")
    lines.append("    RESPOND MSG=\"ACTIVATION YMS-1\"")
    lines.append("    SAVE_VARIABLE VARIABLE=active_tool VALUE=1")
    lines.append("  {% else %}")
    lines.append("    RESPOND MSG=\"YMS INITIALISATION STARTING\"")
    lines.append("    G92 E0")
    lines.append("    SET_KINEMATIC_POSITION E=0")
    lines.append("    SYNC_EXTRUDER_MOTION EXTRUDER=extruder MOTION_QUEUE=extruder")
    for name in all_ext:
        lines.append(f"    SYNC_EXTRUDER_MOTION EXTRUDER={name} MOTION_QUEUE=\"\"")
    lines.append("    SAVE_VARIABLE VARIABLE=active_tool VALUE=0")
    lines.append("    MOTION_SENSOR_INIT")
    for i in range(yms_count):
        lines.append(f"    SET_FILAMENT_SENSOR SENSOR=YMS-{i+1} ENABLE=1")
    lines.append("    M400")
    lines.append("    SAVE_VARIABLE VARIABLE=yms_sensor_initialisation VALUE=True")
    lines.append("    RESPOND MSG=\"INSERT NEXT FILAMENT\"")
    lines.append("  {% endif %}")
    lines.append("")

    # T1..TN
    for t in range(1, yms_count):
        yms_num = t + 1
        lines.append(f"[gcode_macro T{t}]")
        lines.append("gcode:")
        lines.append("  {% set svv = printer.save_variables.variables %}")
        lines.append("  {% if printer.save_variables.variables.printing_start %}")
        for i in range(yms_count):
            lines.append(f"      SET_FILAMENT_SENSOR SENSOR=YMS-{i+1} ENABLE={'1' if i == t else '0'}")
        lines.append("      SYNC_EXTRUDER_MOTION EXTRUDER=extruder MOTION_QUEUE=extruder")
        for i, name in enumerate(all_ext):
            q = "extruder" if i == t else '""'
            lines.append(f"      SYNC_EXTRUDER_MOTION EXTRUDER={name} MOTION_QUEUE={q}")
        lines.append(f"  RESPOND MSG=\"ACTIVATION YMS-{yms_num}\"")
        lines.append("  {% else %}")
        # Insert mode: activate previous tool
        prev = t - 1
        for i in range(yms_count):
            lines.append(f"      SET_FILAMENT_SENSOR SENSOR=YMS-{i+1} ENABLE={'1' if i == prev else '0'}")
        lines.append("      SYNC_EXTRUDER_MOTION EXTRUDER=extruder MOTION_QUEUE=extruder")
        for i, name in enumerate(all_ext):
            q = "extruder" if i == prev else '""'
            lines.append(f"      SYNC_EXTRUDER_MOTION EXTRUDER={name} MOTION_QUEUE={q}")
        lines.append("  {% endif %}")
        lines.append(f"  SAVE_VARIABLE VARIABLE=active_tool VALUE={t}")
        lines.append("")

    # CURRENT_UNLOAD
    lines.append("[gcode_macro CURRENT_UNLOAD]")
    lines.append("gcode:")
    for name in all_ext:
        lines.append(f"      SET_TMC_CURRENT STEPPER={name} CURRENT=0.5 HOLDCURRENT=0.5")
    lines.append("")

    # SET_PRESSURE_ADVANCE override
    lines.append("[gcode_macro SET_PRESSURE_ADVANCE]")
    lines.append("rename_existing: SET_PA_ORIG")
    lines.append("gcode:")
    lines.append("    {% set pa = params.ADVANCE|default(none) %}")
    lines.append("    {% set st = params.SMOOTH_TIME|default(0.040) %}")
    lines.append("    {% if pa is not none %}")
    lines.append("      SET_PA_ORIG EXTRUDER=extruder ADVANCE={pa} SMOOTH_TIME={st}")
    for name in all_ext:
        lines.append(f"      SET_PA_ORIG EXTRUDER={name} ADVANCE={{pa}} SMOOTH_TIME={{st}}")
    lines.append("    {% else %}")
    lines.append("      SET_PA_ORIG {printer.gcode.move_parameters}")
    lines.append("    {% endif %}")

    return "\n".join(lines)


def render_gcode_macros(p):
    """Render gcode macros from the catalog JSON."""
    macros = p.get('gcode_macros', [])
    lines = []
    for macro in macros:
        condition = macro.get('condition', 'always')
        if not check_condition(condition, p):
            continue
        gcode = macro['gcode']
        lines.append(gcode)
    return "\n\n".join(lines)


def render_save_config():
    return """#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#"""


# ─── Assembler ──────────────────────────────────────────────────────

def generate(product_id):
    p = resolve_product(product_id)
    yms = p.get('yms_count', 0)

    sections = [
        render_header(p),
        "",
        render_includes(p),
        "",
        render_probe_pressure(p),
        "",
        render_motor_constants(p),
        "",
        render_tmc_autotune(p),
        "",
        render_mcu(p),
        "",
        render_smartbox_mcu(p),
        "",
        render_printer(p),
        "",
        render_adxl(p),
        "",
        render_steppers(p),
        "",
        render_thermistor(p),
        "",
        render_extruder(p),
        "",
    ]

    if yms == 0:
        sections.append(render_filament_sensor_single(p))
    else:
        sections.append(render_yms_extruders(p))

    sections.extend([
        "",
        render_heater_bed(p),
        "",
        render_verify_heaters(),
        "",
        render_fans(p),
        "",
        render_temp_sensors(),
        "",
        render_probe(p),
        "",
        render_bed_mesh(p),
        "",
        render_screws_tilt(p),
        "",
        render_gcode_macros(p),
        "",
    ])

    if yms > 0:
        sections.append(render_yms_tool_macros(p))
        sections.append("")

    sections.append(render_save_config())
    sections.append("")

    output = "\n".join(sections)
    while "\n\n\n" in output:
        output = output.replace("\n\n\n", "\n\n")
    return output.rstrip() + "\n"


# ─── CLI ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="YUMI Printer CFG Generator")
    parser.add_argument("product", nargs="?", help="Product ID (e.g. C235_DD_LW_04)")
    parser.add_argument("-o", "--output", help="Output file (default: stdout)")
    parser.add_argument("--list", action="store_true", help="List available products")
    args = parser.parse_args()

    if args.list:
        catalog = load_catalog()
        products = catalog.get("products", {})
        for pid, p in products.items():
            if not isinstance(p, dict) or "chain" not in p:
                continue
            chain_str = " → ".join(p["chain"])
            print(f"  {pid:30s} {p['name']:50s} [{chain_str}]")
        return

    if not args.product:
        parser.error("Product ID required. Use --list to see available products.")

    cfg = generate(args.product)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(cfg)
        print(f"Generated: {args.output}")
    else:
        print(cfg)


if __name__ == "__main__":
    main()
