"""
Renderer macros core — PAUSE, RESUME, CANCEL_PRINT, PRINT_START, PRINT_END,
ALL_FAN_OFF, SET_GCODE_OFFSET, LOAD/UNLOAD_FILAMENT, SMART_HOME,
BED_DETECTION, PROBE_CALIBRATE, SCREWS_TILT_CALCULATE, BED_MESH_CALIBRATE,
CALCULATE_Z_OFFSET
"""


def render_pause_resume_cancel(cfg):
    """PAUSE, RESUME, CANCEL_PRINT"""
    output = []

    # PAUSE
    output.append("[gcode_macro PAUSE]")
    output.append("description: Pause the running print")
    output.append("rename_existing: PAUSE_BASE")
    output.append("variable_extrude: 5.0")
    output.append("gcode:")
    output.append("  SAVE_VARIABLE VARIABLE=fan_speed VALUE={printer.fan.speed * 255}")
    output.append("  {% set act_x = printer.toolhead.position.x|float %}")
    output.append("  {% set act_y = printer.toolhead.position.y|float %}")
    output.append("  {% set act_z = printer.toolhead.position.z|float %}")
    output.append("  SAVE_VARIABLE VARIABLE=pause_x VALUE={act_x}")
    output.append("  SAVE_VARIABLE VARIABLE=pause_y VALUE={act_y}")
    output.append("  SAVE_VARIABLE VARIABLE=pause_z VALUE={act_z}")
    output.append("  M106 S0")
    output.append("  {% set E = printer[\"gcode_macro PAUSE\"].extrude|float %}")
    output.append("  {% set x_park = printer.toolhead.axis_maximum.x|float %}")
    output.append("  {% set y_park = printer.toolhead.axis_maximum.y|float / 2 %}")
    output.append("  {% set max_z = printer.toolhead.axis_maximum.z|float %}")
    output.append("  {% set act_z = printer.toolhead.position.z|float %}")
    output.append("  {% if act_z < (max_z - 2.0) %}")
    output.append("    {% set z_safe = 2.0 %}")
    output.append("  {% else %}")
    output.append("    {% set z_safe = max_z - act_z %}")
    output.append("  {% endif %}")
    output.append("  PAUSE_BASE")
    output.append("  G91")
    output.append("  {% if printer.extruder.can_extrude|lower == 'true' %}")
    output.append("    G1 E-{E} F2100")
    output.append("  {% else %}")
    output.append("    {action_respond_info(\"Extruder not hot enough\")}")
    output.append("  {% endif %}")
    output.append("  {% if \"xyz\" in printer.toolhead.homed_axes %}")
    output.append("    G1 Z{z_safe} F900")
    output.append("    G90")
    output.append("    G1 X{x_park} Y{y_park} F6000")
    output.append("  {% else %}")
    output.append("    {action_respond_info(\"Printer not homed\")}")
    output.append("  {% endif %}")
    output.append("  M117 Pause")
    output.append("")

    # RESUME
    output.append("[gcode_macro RESUME]")
    output.append("description: Resume the running print")
    output.append("rename_existing: RESUME_BASE")
    output.append("variable_prime: 40.0")
    output.append("gcode:")
    output.append("  {% set svv = printer.save_variables.variables %}")
    output.append("  {% set fan_speed = svv.fan_speed|default(0)|int %}")
    output.append("  {% set x_park = printer.toolhead.axis_maximum.x|float %}")
    output.append("  G1 X{x_park} F6000")
    output.append("  {% if 'pause_x' in svv and 'pause_y' in svv and 'pause_z' in svv %}")
    output.append("    {% set px = svv.pause_x|float %}")
    output.append("    {% set py = svv.pause_y|float %}")
    output.append("    {% set pz = svv.pause_z|float %}")
    output.append("  {% else %}")
    output.append("    {action_respond_info(\"Pause coordinates not found.\")}")
    output.append("    M117 ERROR: Pause position unknown.")
    output.append("  {% endif %}")
    output.append("  {% set E = printer[\"gcode_macro PAUSE\"].extrude|float %}")
    output.append("  {% if 'VELOCITY' in params|upper %}")
    output.append("    {% set get_params = ('VELOCITY=' + params.VELOCITY) %}")
    output.append("  {% else %}")
    output.append("    {% set get_params = \"\" %}")
    output.append("  {% endif %}")
    output.append("  {% if printer.extruder.can_extrude|lower == 'true' %}")
    output.append("    G91")
    output.append("    G1 E{prime|float} F300")
    output.append("    G92 E0")
    output.append("    M106 S255")
    output.append("    G4 P5000")
    output.append("    G90")
    output.append("    G1 X{x_park - 11} F26000")
    output.append("    G92 E0")
    output.append("    G1 X{px} Y{py} Z{pz} F6000")
    output.append("    G1 E{E} F10800")
    output.append("    M106 S{fan_speed}")
    output.append("  {% else %}")
    output.append("    {action_respond_info(\"Extruder not hot enough\")}")
    output.append("  {% endif %}")
    output.append("  RESUME_BASE {get_params}")
    output.append("  M117 Printing...")
    output.append("")

    # CANCEL_PRINT
    output.append("[gcode_macro CANCEL_PRINT]")
    output.append("rename_existing: CANCEL_PRINT_DEFAULT")
    output.append("description: Cancel print, retract and park head safely")
    output.append("gcode:")
    output.append("  M220 S100")
    output.append("  M221 S100")
    output.append("  SAVE_VARIABLE VARIABLE=was_interrupted VALUE=False")
    output.append("  SAVE_VARIABLE VARIABLE=printing_start VALUE=False")
    output.append("  {% set retract_mm = 20.0 %}")
    output.append("  {% set z_lift = 10.0 %}")
    output.append("  {% set x_park = printer.configfile.settings['stepper_x']['position_max']|float %}")
    output.append("  {% set y_park = printer.configfile.settings['stepper_y']['position_max']|float %}")
    output.append("  {% set z_max = printer.toolhead.axis_maximum.z|float %}")
    output.append("  {% set minT = printer.configfile.settings['extruder']['min_extrude_temp']|float %}")
    output.append("  SET_VELOCITY_LIMIT ACCEL=20000 ACCEL_TO_DECEL=10000")
    output.append("  {% if printer.extruder.temperature >= minT %}")
    output.append("    G1 E-{retract_mm} F11000")
    output.append("    G92 E0")
    output.append("  {% endif %}")
    output.append("  G91")
    output.append("  {% set dz = z_lift if (printer.gcode_move.position.z + z_lift) < z_max else (z_max - printer.gcode_move.position.z) %}")
    output.append("  G1 Z+{dz} F3000")
    output.append("  G90")
    output.append("  G1 X{x_park} F9000")
    output.append("  G1 Y{y_park} F3000")
    output.append("  G92 E0")
    output.append("  G1 E-15 F100")
    output.append("  G92 E0")
    output.append("  G1 E-10 F100")
    output.append("  G92 E0")
    output.append("  G1 E-85 F4000")
    output.append("  ALL_FAN_OFF")
    output.append("  TURN_OFF_HEATERS")
    output.append("  M84")
    output.append("  {action_respond_info(\"Cancel Print executed\")}")
    output.append("  CANCEL_PRINT_DEFAULT")
    output.append("")

    return "\n".join(output)


def render_print_start_end(cfg):
    """PRINT_START, PRINT_END, ALL_FAN_OFF"""
    output = []

    output.append("[gcode_macro PRINT_START]")
    output.append("gcode:")
    output.append("  G92 E0")
    output.append("")

    output.append("[gcode_macro PRINT_END]")
    output.append("description: Safety stop — slicer does real parking")
    output.append("gcode:")
    output.append("  ALL_FAN_OFF")
    output.append("  TURN_OFF_HEATERS")
    output.append("  M84")
    output.append("")

    output.append("[gcode_macro ALL_FAN_OFF]")
    output.append("description: Turn off all fans")
    output.append("gcode:")
    output.append("  M107")
    output.append("")

    return "\n".join(output)


def render_filament_macros(cfg):
    """LOAD_FILAMENT, UNLOAD_FILAMENT"""
    output = []

    output.append("[gcode_macro UNLOAD_FILAMENT]")
    output.append("description: Unload filament from hotend")
    output.append("gcode:")
    output.append("  {% if printer.extruder.temperature < 200 %}")
    output.append("    M109 S200")
    output.append("  {% endif %}")
    output.append("  G90")
    output.append("  G1 X0 F5000")
    output.append("  G1 X-12 F2000")
    output.append("  G92 E0")
    output.append("  G1 E-30 F800")
    output.append("  G1 X20 F5000")
    output.append("")

    output.append("[gcode_macro LOAD_FILAMENT]")
    output.append("description: Load filament into hotend")
    output.append("gcode:")
    output.append("  {% if printer.extruder.temperature < 200 %}")
    output.append("    M109 S200")
    output.append("  {% endif %}")
    output.append("  G91")
    output.append("  G1 E50 F800")
    output.append("  G1 E30 F150")
    output.append("  G90")
    output.append("")

    return "\n".join(output)


def render_gcode_offset(cfg):
    """SET_GCODE_OFFSET persistent"""
    output = []

    output.append("[gcode_macro SET_GCODE_OFFSET]")
    output.append("rename_existing: _SET_GCODE_OFFSET")
    output.append("gcode:")
    output.append("  {% if printer.save_variables.variables.gcode_offsets %}")
    output.append("    {% set offsets = printer.save_variables.variables.gcode_offsets %}")
    output.append("  {% else %}")
    output.append("    {% set offsets = {'x': None,'y': None,'z': None} %}")
    output.append("  {% endif %}")
    output.append("  {% set ns = namespace(offsets={'x': offsets.x,'y': offsets.y,'z': offsets.z}) %}")
    output.append("  _SET_GCODE_OFFSET {% for p in params %}{'%s=%s '% (p, params[p])}{% endfor %}")
    output.append("  {%if 'X' in params %}{% set null = ns.offsets.update({'x': params.X}) %}{% endif %}")
    output.append("  {%if 'Y' in params %}{% set null = ns.offsets.update({'y': params.Y}) %}{% endif %}")
    output.append("  {%if 'Z' in params %}{% set null = ns.offsets.update({'z': params.Z}) %}{% endif %}")
    output.append("  {%if 'Z_ADJUST' in params %}")
    output.append("    {%if ns.offsets.z == None %}{% set null = ns.offsets.update({'z': 0}) %}{% endif %}")
    output.append("    {% set null = ns.offsets.update({'z': (ns.offsets.z | float) + (params.Z_ADJUST | float)}) %}")
    output.append("  {% endif %}")
    output.append("  SAVE_VARIABLE VARIABLE=gcode_offsets VALUE=\"{ns.offsets}\"")
    output.append("")

    return "\n".join(output)


def render_calibration_macros(cfg):
    """PID_BED, PID_HOTEND, ADXL, SAVECONFIG, SMART_HOME"""
    output = []

    output.append("[gcode_macro PID_BED]")
    output.append("description: PID calibration for bed")
    output.append("gcode:")
    output.append("  {% if printer.idle_timeout.state == \"Printing\" %}")
    output.append("    {action_respond_info(\"Can't run during print!\")}")
    output.append("  {% else %}")
    output.append("    {% if printer.toolhead.homed_axes != \"xyz\" %}")
    output.append("      G28")
    output.append("    {% endif %}")
    output.append("    G1 Z50 F1500")
    output.append("    M400")
    output.append("    PID_CALIBRATE HEATER=heater_bed TARGET={params.TEMP|default(65)}")
    output.append("  {% endif %}")
    output.append("")

    output.append("[gcode_macro PID_HOTEND]")
    output.append("description: PID calibration for hotend")
    output.append("gcode:")
    output.append("  {% if printer.idle_timeout.state == \"Printing\" %}")
    output.append("    {action_respond_info(\"Can't run during print!\")}")
    output.append("  {% else %}")
    output.append("    {% if printer.toolhead.homed_axes != \"xyz\" %}")
    output.append("      G28")
    output.append("    {% endif %}")
    output.append("    G1 Z50 F1500")
    output.append("    M400")
    output.append("    M106")
    output.append("    PID_CALIBRATE HEATER=extruder TARGET={params.TEMP|default(220)}")
    output.append("    M107")
    output.append("  {% endif %}")
    output.append("")

    output.append("[gcode_macro ADXL_AXE_X]")
    output.append("description: Resonance test X axis")
    output.append("gcode:")
    output.append("  {% if printer.toolhead.homed_axes != \"xyz\" %}")
    output.append("    G28")
    output.append("  {% endif %}")
    output.append("  M400")
    output.append("  SHAPER_CALIBRATE AXIS=X")
    output.append("")

    output.append("[gcode_macro ADXL_AXE_Y]")
    output.append("description: Resonance test Y axis")
    output.append("gcode:")
    output.append("  {% if printer.toolhead.homed_axes != \"xyz\" %}")
    output.append("    G28")
    output.append("  {% endif %}")
    output.append("  M400")
    output.append("  SHAPER_CALIBRATE AXIS=Y")
    output.append("")

    output.append("[gcode_macro SAVECONFIG]")
    output.append("description: Save configuration")
    output.append("gcode:")
    output.append("  SAVE_CONFIG")
    output.append("")

    output.append("[gcode_macro SMART_HOME]")
    output.append("description: Home all axes safely")
    output.append("gcode:")
    output.append("  G28 XY")
    output.append("  G1 X30 Y200 F6000")
    output.append("  G4 P1000")
    output.append("  G28 Z")
    output.append("  G1 Z10")
    output.append("")

    return "\n".join(output)


def render_bed_detection_macros(cfg):
    """BED_DETECTION, PROBE_CALIBRATE, SCREWS_TILT_CALCULATE, BED_MESH_CALIBRATE overrides"""
    output = []

    output.append("[gcode_macro BED_DETECTION]")
    output.append("gcode:")
    output.append("  {% set x_park = printer.configfile.settings['stepper_x']['position_max']|float %}")
    output.append("  {% set y_park = printer.configfile.settings['stepper_y']['position_max']|float %}")
    output.append("  {% set z_max = printer.configfile.settings['stepper_z']['position_max']|float %}")
    output.append("  G28 X")
    output.append("  G28 Y")
    output.append("  SET_KINEMATIC_POSITION Z={z_max - 20}")
    output.append("  G90")
    output.append("  G1 X{x_park / 2 - 19} Y{y_park - 23} F12000")
    output.append("  PROBE")
    output.append("  SET_KINEMATIC_POSITION Z=0")
    output.append("  G1 Z10 F500")
    output.append("  G1 X{x_park - 14} Y{y_park - 23} F12000")
    output.append("  PROBE")
    output.append("  SET_KINEMATIC_POSITION Z=0")
    output.append("  G1 Z10 F500")
    output.append("  G1 X{x_park} F9000")
    output.append("  G1 Y{y_park - 2} F12000")
    output.append("")

    output.append("[gcode_macro PROBE_CALIBRATE]")
    output.append("rename_existing: BASE_PROBE_CALIBRATE")
    output.append("gcode:")
    output.append("  {% set x_park = printer.configfile.settings['stepper_x']['position_max']|float %}")
    output.append("  {% set y_park = printer.configfile.settings['stepper_y']['position_max']|float %}")
    output.append("  BED_DETECTION")
    output.append("  G1 X{x_park / 2} Y{y_park / 2} F12000")
    output.append("  BASE_PROBE_CALIBRATE")
    output.append("")

    output.append("[gcode_macro SCREWS_TILT_CALCULATE]")
    output.append("rename_existing: BASE_SCREWS_TILT_CALCULATE")
    output.append("gcode:")
    output.append("  {% set x_park = printer.configfile.settings['stepper_x']['position_max']|float %}")
    output.append("  {% set y_park = printer.configfile.settings['stepper_y']['position_max']|float %}")
    output.append("  BED_DETECTION")
    output.append("  M190 S65")
    output.append("  BASE_SCREWS_TILT_CALCULATE")
    output.append("  G1 X{x_park / 2} Y{y_park - 2} F6000")
    output.append("  G1 Z20 F500")
    output.append("  M140 S0")
    output.append("")

    output.append("[gcode_macro BED_MESH_CALIBRATE]")
    output.append("rename_existing: BASE_BED_MESH_CALIBRATE")
    output.append("description: Bed mesh with preheat and auto homing")
    output.append("gcode:")
    output.append("  {% set profile_name = params.PROFILE|default('default')|string %}")
    output.append("  BED_DETECTION")
    output.append("  G1 Z100")
    output.append("  M190 S65")
    output.append("  G4 P60000")
    output.append("  BASE_BED_MESH_CALIBRATE PROFILE={profile_name}")
    output.append("  BED_MESH_PROFILE SAVE={profile_name}")
    output.append("  SAVE_CONFIG")
    output.append("")

    # CALCULATE_Z_OFFSET (si probe_pressure)
    if "probe_pressure" in cfg:
        output.append("[gcode_macro CALCULATE_Z_OFFSET]")
        output.append("description: Calculate Z offset via pressure probe")
        output.append("gcode:")
        output.append("  {% set SAVE_PARAM = params.SAVE|default(0)|int %}")
        output.append("  YUMI_CALCULATE_Z_OFFSET SAVE={SAVE_PARAM}")
        output.append("")

    return "\n".join(output)


def render_marlin_compat(cfg):
    """M201, M203, M205, M900, M106/M107 overrides"""
    output = []

    # M106 override (Aux_Fan sur P2, Motherboard sur P3)
    output.append("[gcode_macro M106]")
    output.append("rename_existing: G106")
    output.append("gcode:")
    output.append("  {% if params.P is defined %}")
    output.append("    {% if params.P|int == 2 %}")
    output.append("      {% if params.S is defined %}")
    output.append("        {% if params.S|int == 255 %}")
    output.append("          {% set realspeed = 1 %}")
    output.append("        {% elif params.S|int == 0 %}")
    output.append("          {% set realspeed = 0 %}")
    output.append("        {% else %}")
    output.append("          {% set realspeed = params.S|float/255 %}")
    output.append("        {% endif %}")
    output.append("      {% else %}")
    output.append("        {% set realspeed = 1 %}")
    output.append("      {% endif %}")
    output.append("      SET_FAN_SPEED FAN=Aux_Fan SPEED={realspeed}")
    output.append("    {% endif %}")
    output.append("  {% else %}")
    output.append("    {% if params.S is defined %}")
    output.append("      G106 S{params.S}")
    output.append("    {% else %}")
    output.append("      G106 S255")
    output.append("    {% endif %}")
    output.append("  {% endif %}")
    output.append("")

    # M107 override
    output.append("[gcode_macro M107]")
    output.append("rename_existing: G107")
    output.append("gcode:")
    output.append("  {% if params.P is defined %}")
    output.append("    {% if params.P|int == 2 %}")
    output.append("      SET_FAN_SPEED FAN=Aux_Fan SPEED=0")
    output.append("    {% endif %}")
    output.append("  {% else %}")
    output.append("    SET_FAN_SPEED FAN=Aux_Fan SPEED=0")
    output.append("    G107")
    output.append("  {% endif %}")
    output.append("")

    # M201
    output.append("[gcode_macro M201]")
    output.append("description: Sets maximum acceleration.")
    output.append("variable_max_accel: 1.7976931348623157e+308")
    output.append("gcode:")
    output.append("  {% if 'X' in params or 'Y' in params %}")
    output.append("    {% set accel = (params.X|default(params.Y)|float, params.Y|default(params.X)|float)|min %}")
    output.append("    SET_GCODE_VARIABLE MACRO=M201 VARIABLE=max_accel VALUE=\"{accel}\"")
    output.append("  {% else %}")
    output.append("    SET_VELOCITY_LIMIT")
    output.append("  {% endif %}")
    output.append("")

    # M203
    output.append("[gcode_macro M203]")
    output.append("description: Sets maximum velocity.")
    output.append("gcode:")
    output.append("  {% if 'X' in params or 'Y' in params %}")
    output.append("    {% set velocity = (params.X|default(params.Y)|float, params.Y|default(params.X)|float)|min %}")
    output.append("    SET_VELOCITY_LIMIT VELOCITY=\"{velocity}\"")
    output.append("  {% else %}")
    output.append("    SET_VELOCITY_LIMIT")
    output.append("  {% endif %}")
    output.append("")

    # M205
    output.append("[gcode_macro M205]")
    output.append("description: Sets square corner velocity.")
    output.append("gcode:")
    output.append("  {% if 'X' in params or 'Y' in params %}")
    output.append("    SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=\"{(params.X|default(0)|float, params.Y|default(0)|float)|min}\"")
    output.append("  {% else %}")
    output.append("    SET_VELOCITY_LIMIT")
    output.append("  {% endif %}")
    output.append("")

    # M900
    output.append("[gcode_macro M900]")
    output.append("description: Set pressure advance (Marlin compat)")
    output.append("gcode:")
    output.append("  {% if 'K' in params %}")
    output.append("    {% if 'E' in params %}")
    output.append("      SET_PRESSURE_ADVANCE EXTRUDER={params.E} ADVANCE={params.K}")
    output.append("    {% else %}")
    output.append("      SET_PRESSURE_ADVANCE ADVANCE={params.K}")
    output.append("    {% endif %}")
    output.append("  {% endif %}")
    output.append("")

    return "\n".join(output)
