#!/bin/bash
#
# Yumi CFG Generator — Firstboot
#
# Oneshot : scan hardware → generate printer.cfg → done
# Si printer.cfg existe deja et contient "Generated by Yumi CFG Generator" → skip
#
# Appele par yumi-cfg-firstboot.service au premier boot

set -e

# User setup
if [ -n "$SUDO_USER" ] && [ "$SUDO_USER" != "runner" ]; then
    OWNER="$SUDO_USER"
    USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    OWNER="${OWNER:-pi}"
    USER_HOME="/home/$OWNER"
fi

PRINTER_CFG="$USER_HOME/printer_data/config/printer.cfg"
YUMI_CONFIG_DIR="$USER_HOME/yumi-config"
GENERATOR_DIR="$YUMI_CONFIG_DIR/generator"
LOCK_FILE="/tmp/yumi-cfg-firstboot.lock"

echo "[yumi-cfg-firstboot] Starting..."
echo "[yumi-cfg-firstboot] User: $OWNER | Home: $USER_HOME"

# Skip if already configured
if [ -f "$PRINTER_CFG" ]; then
    if grep -q "Generated by Yumi CFG Generator" "$PRINTER_CFG" 2>/dev/null; then
        echo "[yumi-cfg-firstboot] printer.cfg already generated, skipping"
        exit 0
    fi
    if [ -s "$PRINTER_CFG" ]; then
        echo "[yumi-cfg-firstboot] printer.cfg exists and not empty, skipping (manual config)"
        exit 0
    fi
fi

# Lock to prevent concurrent runs
if [ -f "$LOCK_FILE" ]; then
    echo "[yumi-cfg-firstboot] Already running (lock exists), exiting"
    exit 0
fi
touch "$LOCK_FILE"
trap "rm -f $LOCK_FILE" EXIT

# Check generator exists
if [ ! -f "$GENERATOR_DIR/engine.py" ]; then
    echo "[yumi-cfg-firstboot] ERROR: generator/engine.py not found at $GENERATOR_DIR"
    exit 1
fi

# Run scanner to detect hardware
echo "[yumi-cfg-firstboot] Scanning hardware..."
SCAN_RESULT=$(python3 "$GENERATOR_DIR/scanner.py" --json 2>/dev/null)

if [ -z "$SCAN_RESULT" ]; then
    echo "[yumi-cfg-firstboot] ERROR: Scanner returned empty result"
    exit 1
fi

# Extract parameters from scan
YMS_COUNT=$(echo "$SCAN_RESULT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('yms_count_detected', 2))")
SMARTBOX=$(echo "$SCAN_RESULT" | python3 -c "import sys,json; d=json.load(sys.stdin); print('yes' if d.get('smartbox_detected') else 'no')")

echo "[yumi-cfg-firstboot] Detected: YMS=$YMS_COUNT, Smartbox=$SMARTBOX"

# Determine model from environment or default
# Can be set via /boot/yumi_model or environment variable
MODEL="C235"
if [ -f "/boot/yumi_model" ]; then
    MODEL=$(cat /boot/yumi_model | tr -d '[:space:]')
fi
if [ -n "$YUMI_MODEL" ]; then
    MODEL="$YUMI_MODEL"
fi

echo "[yumi-cfg-firstboot] Model: $MODEL"

# Generate printer.cfg
echo "[yumi-cfg-firstboot] Generating printer.cfg..."
python3 "$GENERATOR_DIR/engine.py" \
    --model "$MODEL" \
    --yms "$YMS_COUNT" \
    --hotend chroma_x12 \
    --output "$PRINTER_CFG"

if [ $? -ne 0 ]; then
    echo "[yumi-cfg-firstboot] ERROR: Generation failed"
    exit 1
fi

# Fix ownership
chown "$OWNER:$OWNER" "$PRINTER_CFG"

LINES=$(wc -l < "$PRINTER_CFG")
echo "[yumi-cfg-firstboot] SUCCESS: printer.cfg generated ($LINES lines)"
echo "[yumi-cfg-firstboot] Model=$MODEL, YMS=$YMS_COUNT, Smartbox=$SMARTBOX"

# Restart klipper to load the new config
if systemctl is-active --quiet klipper; then
    echo "[yumi-cfg-firstboot] Restarting Klipper..."
    systemctl restart klipper
fi

echo "[yumi-cfg-firstboot] Done."
